name: Create Hotfix Tag
on:
  pull_request:
    type: [closed]
    branches: [main]
jobs:
    hotfix-tagging:
        if: ${{ github.event.pull_request.merged == true }}
        name: create hotfix tag
        runs-on: ubuntu-latest
        steps:
        - name: checkout to main
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            ref: main

        - name: tagging version
          run: |
            HOTFIX_VERSION=`git describe --tags --abbrev=0 | awk -F. '{OFS="."; $NF+=1; print $0}'`
            git tag $HOTFIX_VERSION
            git push origin $HOTFIX_VERSION
