name: Cypress Tests

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: component test on Node 16
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: component
          component: true
          browser: chrome