name: Label issues

on:
  pull_request:
    branches:
      - develop

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Extract Prefix and Add Label
        uses: actions/github-script@v6
        with:
          script: |
            const ref = "${{ github.event.pull_request.head.ref }}"
            const prefix = ref.split('/')[0]
            
            console.log(context.number)
            console.log(context.owner, context.repo, context.repo.owner, context.repo.repo)
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [prefix],
            })
