name: Label issues

on:
  pull_request:
    branches:
      - develop

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Extract Prefix and Add Label
        uses: actions/github-script@v6
        with:
          script: |
            const ref = "${{ github.event.pull_request.head.ref }}"
            const prefix = ref.split('/')[0]

            const logger = "${{ github.head_ref }}"
            const logger2 = "${{ github.ref_name }}"

            console.log(logger)
            console.log(logger2)

            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [prefix],
            })
