name: Extract Branch Prefix and Add Label

permissions:
  pull-requests: write

on:
  pull_request:
    branches:
      - develop

jobs:
  add-label-to-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Add Label to Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = "${{github.head_ref}}";
            const prefix = branchName.split('/')[0];
            
            if(['hotfix', 'feature'].includes(prefix)){
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [prefix],
              });
            };
