name: When Pull Request Opened Activated

on:
  pull_request:
    types: [opened, closed]
    branches:
      - develop

jobs:
  do-nothing:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Opened And Closed
        run: echo "Do Nothing"
