name: Label issues

on:
  pull_request:
    branches:
      - develop

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Extract Prefix from Branch Name
        id: extract_prefix
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          PREFIX=$(echo "$BRANCH_NAME" | cut -d'/' -f1)
          echo "prefix=$PREFIX" >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v6
        with:
          script: |
            const label = "${{ steps.extract_prefix.outputs.prefix }}"
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [label],
            })
