# 정기배포
# jira automation을 통해 해당 workflow를 실행
# release 브랜치가 있다면 main 브랜치에 merge & push.
name: Regular Deployment
on:
  repository_dispatch:
    types: [regular-deployment]
jobs:
    merge-release:
        runs-on: ubuntu-latest
        steps:
          - name: Check log
            run: |
              if [[ ${{contains(github.head_ref, 'hotfix')}} == true ]]; then
                echo "release branch is not exist"
              else
                echo ${{ github.head_ref }}
                echo ${{ github.ref }}
              fi
