# 정기배포
# jira automation을 통해 해당 workflow를 실행
# release 브랜치가 있다면 main 브랜치에 merge & push.
name: Regular Deployment
on:
  repository_dispatch:
    types: [regular-deployment]
jobs:
    merge-release:
        runs-on: ubuntu-latest
        steps:
          - name: checkout to main
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              ref: main
          - name: Check log
            run: |
              RELEASE_VERSION="${{github.event.client_payload.releaseVersion}}"
              echo $RELEASE_VERSION
