name: Create Release Branch
on:
  schedule:
    # 매주 금요일 오후 2시
    - cron: '00 14 * * 5'
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    name: create release branch if there are commits to release on develop
    steps:
      - name: Checkout to develop
        uses: actions/checkout@v3
      - name: Create Release Branch
        if: ${{ git diff --name-only develop main | wc -l > 0 }}
        run: |
          RELEASE_VERSION_NAME=release/v0.0.1
          git config user.name spendit-deployer
          git config user.email server@spendit.kr
          git branch $RELEASE_VERSION_NAME
          git push origin $RELEASE_VERSION_NAME