name: Create Release Branch
on:
  schedule:
    # 매주 금요일 오후 2시
    - cron: '00 14 * * 5'
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    name: create release branch if there are commits to release on develop
    steps:
      - name: Checkout to develop
        uses: actions/checkout@v3
        run: |
          echo ${{ github.head_ref }}